"""initial_schema

Revision ID: bf2af9227ee2
Revises: 
Create Date: 2026-09-05 16:51:04.447896

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2af9227ee2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code')
    )
    # GeoAlchemy2 creates the spatial index automatically when the Geography column is added.
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'province', name='uq_city_name_province')
    )
    # GeoAlchemy2 creates the spatial index automatically.
    op.create_table('search_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('parsed_criteria', sa.JSON(), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='searchrunstatus'), nullable=False),
    sa.Column('compared_to_run_id', sa.UUID(), nullable=True),
    sa.Column('comparison_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['compared_to_run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poi_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query', 'city_id', name='uq_poi_cache_query_city')
    )
    op.create_index('ix_poi_cache_fetched_at', 'poi_cache', ['fetched_at'], unique=False)
    op.create_table('rent_price_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('price_per_sqm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('criteria_breakdown', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'city_id', name='uq_search_result_run_city')
    )
    op.create_table('weather_normals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('avg_sunny_days_year', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_normals')
    op.drop_table('search_results')
    op.drop_table('rent_price_index')
    op.drop_index('ix_poi_cache_fetched_at', table_name='poi_cache')
    op.drop_table('poi_cache')
    op.drop_table('search_runs')
    op.drop_table('cities')
    op.drop_table('airports')
    # ### end Alembic commands ###
